#!/bin/bash

#SBATCH --job-name=plotting
#SBATCH --output=plotting.%j.out
#SBATCH --cpus-per-task=8
#SBATCH --time=70:00:00
#SBATCH --partition=purrlab_students
#SBATCH --mem=32G
#SBATCH --mail-type=START,FAIL,END          # Send an email when the job finishes or fails

module load Anaconda3

cd /home/resy_nizp/MedCLIP_subgroup

# make create_environment

source activate MedCLIP_subgroup

#cd src/data

make plotting