#!/bin/bash

#SBATCH --job-name=run_medclip
#SBATCH --output=run_medclip.%j.out
#SBATCH --cpus-per-task=8
#SBATCH --time=70:00:00
#SBATCH --partition=purrlab_students
#SBATCH --mem=32G
#SBATCH --mail-type=START,FAIL,END          # Send an email when the job finishes or fails

module load Anaconda3

cd /home/resy_nizp/MedCLIP_subgroup

source activate MedCLIP_subgroup

which python
python --version

make requirements

make run_medclip